// Purpose: Public entry for the provider runtime event model. Re-exports the complete,
//   stable surface from the cohesive sub-modules (shared base, payloads, events).
//   No runtime logic — effect/Schema + TS types only.
// Layer: contracts (schema-only). Imported across server, web, and shared.
// Exports: see the explicit re-export lists below — value schemas (const), helpers, and all types.

// --- Shared base schemas, literals, and the common event base ---
export {
  CanonicalItemType,
  CanonicalRequestType,
  isToolLifecycleItemType,
  ProviderRuntimeEventType,
  ProviderRuntimeSourceRef,
  RuntimeEventRaw,
  ThreadTokenUsageSnapshot,
  ToolLifecycleItemType,
  TOOL_LIFECYCLE_ITEM_TYPES,
} from "./providerRuntime.shared";
export type {
  ProviderRefs,
  ProviderRequestId,
  ProviderRuntimeEventBase,
  RuntimeContentStreamKind,
  RuntimeErrorClass,
  RuntimeEventRawSource,
  RuntimeItemStatus,
  RuntimeSessionExitKind,
  RuntimeSessionState,
  RuntimeTaskStatus,
  RuntimeThreadState,
  RuntimeTurnState,
} from "./providerRuntime.shared";

// --- Per-event payloads and their supporting structs ---
export {
  CodexGeneratedImageArtifact,
  CODEX_GENERATED_IMAGE_ARTIFACT_KIND,
  ItemLifecyclePayload,
  UserInputQuestion,
  WorkflowAgentPlan,
  WorkflowAgentRuntimeSnapshot,
  WorkflowAgentSnapshot,
  WorkflowPhase,
} from "./providerRuntime.payloads";
export type {
  AccountRateLimitsUpdatedPayload,
  AccountUpdatedPayload,
  AuthStatusPayload,
  ConfigWarningPayload,
  ContentDeltaPayload,
  DeprecationNoticePayload,
  FilesPersistedPayload,
  HookCompletedPayload,
  HookProgressPayload,
  HookStartedPayload,
  McpOauthCompletedPayload,
  McpStatusUpdatedPayload,
  ModelReroutedPayload,
  ProviderUnhandledPayload,
  RequestOpenedPayload,
  RequestResolvedPayload,
  RuntimeErrorPayload,
  RuntimeTaskListItem,
  RuntimeWarningPayload,
  SessionConfiguredPayload,
  SessionExitedPayload,
  SessionStartedPayload,
  SessionStateChangedPayload,
  TaskCompletedPayload,
  TaskProgressPayload,
  TaskStartedPayload,
  TaskUpdatedPayload,
  ThreadMetadataUpdatedPayload,
  ThreadRealtimeAudioDeltaPayload,
  ThreadRealtimeClosedPayload,
  ThreadRealtimeErrorPayload,
  ThreadRealtimeItemAddedPayload,
  ThreadRealtimeStartedPayload,
  ThreadStartedPayload,
  ThreadStateChangedPayload,
  ThreadTokenUsageUpdatedPayload,
  ToolProgressPayload,
  ToolSummaryPayload,
  TurnAbortedPayload,
  TurnCompletedPayload,
  TurnDiffUpdatedPayload,
  TurnProposedCompletedPayload,
  TurnProposedDeltaPayload,
  TurnStartedPayload,
  TurnTasksUpdatedPayload,
  UserInputQuestionOption,
  UserInputRequestedPayload,
  UserInputResolvedPayload,
} from "./providerRuntime.payloads";

// --- Per-event structs, the discriminated union, and legacy aliases ---
export {
  ProviderRuntimeEvent,
  ProviderRuntimeEventV2,
  ProviderRuntimeTurnStatus,
} from "./providerRuntime.events";
export type {
  ProviderRuntimeAccountRateLimitsUpdatedEvent,
  ProviderRuntimeAccountUpdatedEvent,
  ProviderRuntimeApprovalRequestedEvent,
  ProviderRuntimeApprovalResolvedEvent,
  ProviderRuntimeAuthStatusEvent,
  ProviderRuntimeConfigWarningEvent,
  ProviderRuntimeContentDeltaEvent,
  ProviderRuntimeDeprecationNoticeEvent,
  ProviderRuntimeErrorEvent,
  ProviderRuntimeUnhandledEvent,
  ProviderRuntimeFilesPersistedEvent,
  ProviderRuntimeHookCompletedEvent,
  ProviderRuntimeHookProgressEvent,
  ProviderRuntimeHookStartedEvent,
  ProviderRuntimeItemCompletedEvent,
  ProviderRuntimeItemStartedEvent,
  ProviderRuntimeItemUpdatedEvent,
  ProviderRuntimeMcpOauthCompletedEvent,
  ProviderRuntimeMcpStatusUpdatedEvent,
  ProviderRuntimeMessageCompletedEvent,
  ProviderRuntimeMessageDeltaEvent,
  ProviderRuntimeModelReroutedEvent,
  ProviderRuntimeRequestOpenedEvent,
  ProviderRuntimeRequestResolvedEvent,
  ProviderRuntimeSessionConfiguredEvent,
  ProviderRuntimeSessionExitedEvent,
  ProviderRuntimeSessionStartedEvent,
  ProviderRuntimeSessionStateChangedEvent,
  ProviderRuntimeTaskCompletedEvent,
  ProviderRuntimeTaskProgressEvent,
  ProviderRuntimeTaskStartedEvent,
  ProviderRuntimeTaskUpdatedEvent,
  ProviderRuntimeThreadMetadataUpdatedEvent,
  ProviderRuntimeThreadRealtimeAudioDeltaEvent,
  ProviderRuntimeThreadRealtimeClosedEvent,
  ProviderRuntimeThreadRealtimeErrorEvent,
  ProviderRuntimeThreadRealtimeItemAddedEvent,
  ProviderRuntimeThreadRealtimeStartedEvent,
  ProviderRuntimeThreadStartedEvent,
  ProviderRuntimeThreadStateChangedEvent,
  ProviderRuntimeThreadTokenUsageUpdatedEvent,
  ProviderRuntimeToolCompletedEvent,
  ProviderRuntimeToolKind,
  ProviderRuntimeToolProgressEvent,
  ProviderRuntimeToolStartedEvent,
  ProviderRuntimeToolSummaryEvent,
  ProviderRuntimeTurnAbortedEvent,
  ProviderRuntimeTurnCompletedEvent,
  ProviderRuntimeTurnDiffUpdatedEvent,
  ProviderRuntimeTurnProposedCompletedEvent,
  ProviderRuntimeTurnProposedDeltaEvent,
  ProviderRuntimeTurnStartedEvent,
  ProviderRuntimeTurnTasksUpdatedEvent,
  ProviderRuntimeUserInputRequestedEvent,
  ProviderRuntimeUserInputResolvedEvent,
  ProviderRuntimeWarningEvent,
} from "./providerRuntime.events";
